/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110322-g13450b6722-20230419"
#endif /* AVUTIL_FFVERSION_H */
